INSERT INTO branches (county, location, contact, capacity) VALUES
('Mombasa', 'Mombasa City', 'contact@mombasa.hosp.ke', 800),
('Kwale', 'Kwale Town', 'contact@kwale.hosp.ke', 400),
('Kilifi', 'Kilifi Town', 'contact@kilifi.hosp.ke', 600),
('Tana River', 'Hola Town', 'contact@tanariver.hosp.ke', 300),
('Lamu', 'Lamu Town', 'contact@lamu.hosp.ke', 250),
('Taita Taveta', 'Voi Town', 'contact@taitataveta.hosp.ke', 350),
('Garissa', 'Garissa Town', 'contact@garissa.hosp.ke', 500),
('Wajir', 'Wajir Town', 'contact@wajir.hosp.ke', 400),
('Mandera', 'Mandera Town', 'contact@mandera.hosp.ke', 300),
('Marsabit', 'Marsabit Town', 'contact@marsabit.hosp.ke', 200),
('Isiolo', 'Isiolo Town', 'contact@isiolo.hosp.ke', 300),
('Meru', 'Meru Town', 'contact@meru.hosp.ke', 700),
('Tharaka Nithi', 'Chuka Town', 'contact@tharaknithi.hosp.ke', 400),
('Embu', 'Embu Town', 'contact@embu.hosp.ke', 500),
('Kitui', 'Kitui Town', 'contact@kitui.hosp.ke', 450),
('Machakos', 'Machakos Town', 'contact@machakos.hosp.ke', 600),
('Makueni', 'Wote Town', 'contact@makueni.hosp.ke', 400),
('Nyandarua', 'Ol Kalou Town', 'contact@nyandarua.hosp.ke', 350),
('Nyeri', 'Nyeri Town', 'contact@nyeri.hosp.ke', 550),
('Kirinyaga', 'Kerugoya Town', 'contact@kirinyaga.hosp.ke', 400),
('Muranga', 'Muranga Town', 'contact@muranga.hosp.ke', 450),
('Kiambu', 'Kiambu Town', 'contact@kiambu.hosp.ke', 700),
('Turkana', 'Lodwar Town', 'contact@turkana.hosp.ke', 300),
('West Pokot', 'Kapenguria Town', 'contact@westpokot.hosp.ke', 250),
('Samburu', 'Maralal Town', 'contact@samburu.hosp.ke', 200),
('Trans Nzoia', 'Kitale Town', 'contact@transnzoia.hosp.ke', 500),
('Uasin Gishu', 'Eldoret Town', 'contact@uasngishu.hosp.ke', 800),
('Elgeyo Marakwet', 'Iten Town', 'contact@elgeyomarakwet.hosp.ke', 300),
('Nandi', 'Kapsabet Town', 'contact@nandi.hosp.ke', 400),
('Baringo', 'Kabarnet Town', 'contact@baringo.hosp.ke', 350),
('Laikipia', 'Nanyuki Town', 'contact@laikipia.hosp.ke', 400),
('Nakuru', 'Nakuru City', 'contact@nakuru.hosp.ke', 900),
('Narok', 'Narok Town', 'contact@narok.hosp.ke', 400),
('Kajiado', 'Kajiado Town', 'contact@kajiado.hosp.ke', 500),
('Kericho', 'Kericho Town', 'contact@kericho.hosp.ke', 450),
('Bomet', 'Bomet Town', 'contact@bomet.hosp.ke', 350),
('Kakamega', 'Kakamega Town', 'contact@kakamega.hosp.ke', 700),
('Vihiga', 'Mbale Town', 'contact@vihiga.hosp.ke', 300),
('Bungoma', 'Bungoma Town', 'contact@bungoma.hosp.ke', 500),
('Busia', 'Busia Town', 'contact@busia.hosp.ke', 400),
('Siaya', 'Siaya Town', 'contact@siaya.hosp.ke', 350),
('Kisumu', 'Kisumu City', 'contact@kisumu.hosp.ke', 800),
('Homa Bay', 'Homa Bay Town', 'contact@homabay.hosp.ke', 400),
('Migori', 'Migori Town', 'contact@migori.hosp.ke', 450),
('Kisii', 'Kisii Town', 'contact@kisii.hosp.ke', 500),
('Nyamira', 'Nyamira Town', 'contact@nyamira.hosp.ke', 300),
('Nairobi', 'Nairobi City', 'contact@nairobi.hosp.ke', 1000);